### PR TITLE
Add darkmode

### PR DESCRIPTION
**Pull request by tomjschwanke**
Added CSS media queries to change the warning site to dark mode if the user has set their OS to darkmode. Colors codes from a chrome mobile screenshot. Feel free to adjust the colors as needed.

### CODE REVIEW

**Comment by tomjschwanke** [comment]
Hi there, it's been a while, could you have a look at this?
Thank you

**Comment by dnorhoj** [comment]
Sorry, totally forgot about it. I'll merge asap

**Review by dnorhoj — APPROVED** [review]

**Comment by tomjschwanke** [comment]
Hi @dnorhoj, any chance of an update on the Firefox Add-on page? I had to build it and get it signed by Mozilla so I could use the updated version, but I would be missing any future updates.
Thanks :)

**Comment by Theblockbuster1** [comment]
@tomjschwanke
dnorhoj told me on Discord that he was planning to make the extension "only block youtube links, for security purposes". It seems he hasn't got round to doing it, and I haven't done it either. When that is implemented it will probably be updated on the Chrome/Firefox stores.

**Comment by dnorhoj** [comment]
Yeah sorry I've got a lot of school and other things to take care of. I'll probably get this fixed in the start of my summer vacation.

**Comment by tomjschwanke** [comment]
Ah okay, thank you both,
Take your time :)

**Pull request merged**
